export const ProcurementEvents = Object.freeze({
  PR_CREATED: "pr.created",
  PR_SUBMITTED: "pr.submitted",
  PR_APPROVED: "pr.approved",
  PR_REJECTED: "pr.rejected",
  PR_SOURCING_STARTED: "pr.sourcing_started",
  PR_SOURCED: "pr.sourced",
  PR_RFQ_PENDING: "pr.rfq_pending",
  PR_RFQ_SENDING: "pr.rfq_sending",
  PR_RFQ_SENT: "pr.rfq_sent",
  PR_AWAITING_REPLIES: "pr.awaiting_replies",
  PR_QUOTES_RECEIVED: "pr.quotes_received",
  PR_ANALYSIS: "pr.analysis",
  PR_COMPLETED: "pr.completed",
  PR_CANCELLED: "pr.cancelled",
  RFQ_CREATED: "rfq.created",
  RFQ_STATUS_UPDATED: "rfq.status_updated",
  VENDOR_RESPONSE_RECEIVED: "vendor_response.received",
  ITEM_STATUS_CHANGED: "pr.item.status_changed",
});
